// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByuvANk9mqUt9IdWwfyqTJ2YBRjYzQt7Y',
    appId: '1:633372699208:web:7b31f417ace1272e1f867d',
    messagingSenderId: '633372699208',
    projectId: 'blooddonation-704',
    authDomain: 'blooddonation-704.firebaseapp.com',
    storageBucket: 'blooddonation-704.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDa9N0flIXEfJQnWHBPiZ2lz2WJnWi5GE',
    appId: '1:633372699208:android:6f6286e2a0c811191f867d',
    messagingSenderId: '633372699208',
    projectId: 'blooddonation-704',
    storageBucket: 'blooddonation-704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyu4GHQJUzzHDkYwLGEp65kl5aRnOtRPM',
    appId: '1:633372699208:ios:02a9d973f2bd8c591f867d',
    messagingSenderId: '633372699208',
    projectId: 'blooddonation-704',
    storageBucket: 'blooddonation-704.appspot.com',
    iosBundleId: 'com.example.lifeblood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyu4GHQJUzzHDkYwLGEp65kl5aRnOtRPM',
    appId: '1:633372699208:ios:7fdd47d07c7f0c241f867d',
    messagingSenderId: '633372699208',
    projectId: 'blooddonation-704',
    storageBucket: 'blooddonation-704.appspot.com',
    iosBundleId: 'com.example.lifeblood.RunnerTests',
  );
}
